### ISSUE TITLE
Why you use a buck converter and aren't the nvme drives overheating??

### ISSUE THREAD

**Issue by systemerror-codenotfound** [j4cbo/tiny5-m2-riser#2]
Just take 3.3V from the X4 slot and use it

Also, those drives need some cooling no?
aren't them overheating?

I have a 3d printable lid that can use a 120mm fan but it's pretty big
https://www.printables.com/es/model/603074-lenovo-tiny-m910q-top-cover-mods

**Comment by galvesribeiro** [comment]
He already explained why he did that [here](https://github.com/badger707/m920q-pcie-bifurcation/issues/1#issuecomment-2035056651).

**Comment by j4cbo** [comment]
I've added some current numbers to the README. As for temperature, the highest I saw during an extended ZFS resilver was 67°C which is within spec.
